import type { DatabaseSync } from 'node:sqlite';
import type { AcrisCellCount, AcrisDocumentEvidence, AcrisQuality, AcrisSourceMetadata, AcrisSummaryData } from '../shared/contracts.js';
import { legalAssociationIdentity, materialMasterSignature, normalizeAcrisMaster, normalizeAcrisParcel, normalizedLegalAssociation } from '../sources/nyc-acris.js';

const MASTER = 'https://data.cityofnewyork.us/resource/bnx9-e6tj.json', LEGALS = 'https://data.cityofnewyork.us/resource/8h5j-fqxa.json', PLUTO = 'https://data.cityofnewyork.us/resource/64uk-42ks.json';
export interface AcrisSnapshotInput { snapshotId: string; retrievedAt: string; complete: boolean; publisherUpdatedAt?: Partial<Record<'master'|'legals'|'pluto', string|null>>; manifest?: Record<string, unknown>; master: Record<string,unknown>[]; legals: Record<string,unknown>[]; parcels: Record<string,unknown>[]; quality?: Record<string, unknown>; }
export interface AcrisIngestResult { snapshotId: string; acceptedDocuments: number; duplicateMasterRows: number; excludedRawTypeCounts: Record<string,number>; legalRows: number; acceptedAssociations: number; duplicateLegalRows: number; invalidBblRows: number; deedsWithoutLegals: number; unmatchedBbls: number; nullCoordinateBbls: number; placedDocumentCells: number; multiBblDocuments: number; }
const value = (db: DatabaseSync, snapshot: string, kind: string, fallback: unknown) => { const row = db.prepare('SELECT value_json FROM acris_quality WHERE snapshot_id=? AND kind=?').get(snapshot, kind) as { value_json?: string } | undefined; try { return row?.value_json ? JSON.parse(row.value_json) : fallback; } catch { return fallback; } };

export function ingestAcrisSnapshot(db: DatabaseSync, input: AcrisSnapshotInput): AcrisIngestResult {
  const result: AcrisIngestResult = { snapshotId: input.snapshotId, acceptedDocuments: 0, duplicateMasterRows: 0, excludedRawTypeCounts: {}, legalRows: input.legals.length, acceptedAssociations: 0, duplicateLegalRows: 0, invalidBblRows: 0, deedsWithoutLegals: 0, unmatchedBbls: 0, nullCoordinateBbls: 0, placedDocumentCells: 0, multiBblDocuments: 0 };
  if (db.prepare('SELECT 1 FROM acris_snapshots WHERE snapshot_id=?').get(input.snapshotId)) return result;
  const masters = new Map<string, Record<string,unknown>>();
  for (const raw of input.master) {
    const type = typeof raw.doc_type === 'string' ? raw.doc_type.trim() : '(missing)';
    if (type !== 'DEED') { result.excludedRawTypeCounts[type] = (result.excludedRawTypeCounts[type] ?? 0) + 1; continue; }
    const normalized = normalizeAcrisMaster(raw); if ('reason' in normalized) throw new Error(`Invalid exact-DEED Master row: ${normalized.reason}`);
    const existing=masters.get(normalized.documentId);
    if (existing) { result.duplicateMasterRows++; if (materialMasterSignature(existing)!==materialMasterSignature(raw)) throw new Error(`ACRIS Master duplicate ${normalized.documentId} disagrees on material event fields; activation refused.`); continue; }
    masters.set(normalized.documentId, raw);
  }
  db.exec('BEGIN IMMEDIATE');
  try {
    db.prepare('INSERT INTO acris_snapshots VALUES(?,?,?,?,?,?,?,?,?,?)').run(input.snapshotId,input.retrievedAt,input.publisherUpdatedAt?.master??null,input.publisherUpdatedAt?.legals??null,input.publisherUpdatedAt?.pluto??null,input.master.length,input.legals.length,input.parcels.length,input.complete?1:0,JSON.stringify(input.manifest??{}));
    if (!input.complete) { db.exec('COMMIT'); return result; }
    const insertDoc = db.prepare('INSERT INTO acris_documents VALUES(?,?,?,?,?)');
    for (const raw of masters.values()) { const n=normalizeAcrisMaster(raw); if ('reason' in n) continue; insertDoc.run(n.documentId,n.recordedDate,n.documentDate,JSON.stringify(n.raw),input.snapshotId); result.acceptedDocuments++; }
    const docIds = new Set(masters.keys()), associations = new Set<string>(), bbls = new Set<string>();
    const insertLegal = db.prepare('INSERT INTO acris_legal_associations VALUES(?,?,?,?,?,?,?,?)');
    for (const raw of input.legals) { const n=normalizedLegalAssociation(raw); if (!docIds.has(n.documentId)) continue; const id=legalAssociationIdentity(raw); if (associations.has(id)) { result.duplicateLegalRows++; continue; } associations.add(id); if (!n.bbl) { result.invalidBblRows++; continue; } bbls.add(n.bbl); insertLegal.run(id,n.documentId,n.bbl,n.easement,n.partialLot,n.airRights,n.subterraneanRights,JSON.stringify(raw)); result.acceptedAssociations++; }
    result.deedsWithoutLegals=(db.prepare('SELECT COUNT(*) AS n FROM acris_documents d WHERE NOT EXISTS(SELECT 1 FROM acris_legal_associations l WHERE l.document_id=d.document_id)').get() as {n:number}).n;
    const insertParcel=db.prepare('INSERT INTO acris_parcels VALUES(?,?,?,?,?,?)'); const parcelBbls=new Set<string>();
    for (const raw of input.parcels) { const n=normalizeAcrisParcel(raw); if ('reason' in n || !bbls.has(n.bbl) || parcelBbls.has(n.bbl)) continue; parcelBbls.add(n.bbl); if (!n.h3Cell) result.nullCoordinateBbls++; insertParcel.run(n.bbl,n.lat,n.lng,n.h3Cell,JSON.stringify(n.raw),input.snapshotId); }
    result.unmatchedBbls=[...bbls].filter(bbl=>!parcelBbls.has(bbl)).length;
    db.prepare("INSERT INTO acris_document_cells SELECT DISTINCT l.document_id,p.h3_cell,'PARCEL_CENTROID' FROM acris_legal_associations l JOIN acris_parcels p ON p.bbl=l.bbl WHERE p.h3_cell IS NOT NULL").run();
    result.placedDocumentCells=(db.prepare('SELECT COUNT(*) AS n FROM acris_document_cells').get() as {n:number}).n;
    result.multiBblDocuments=(db.prepare('SELECT COUNT(*) AS n FROM (SELECT document_id FROM acris_legal_associations GROUP BY document_id HAVING COUNT(DISTINCT bbl)>1)').get() as {n:number}).n;
    const save=db.prepare('INSERT INTO acris_quality VALUES(?,?,?)');
    for (const [kind,data] of Object.entries({ result, ...(input.quality??{}) })) save.run(input.snapshotId,kind,JSON.stringify(data));
    db.exec('COMMIT'); return result;
  } catch(error) { try { db.exec('ROLLBACK'); } catch {} throw error; }
}
function latest(db: DatabaseSync) { return db.prepare('SELECT * FROM acris_snapshots WHERE complete=1 ORDER BY retrieved_at DESC LIMIT 1').get() as {snapshot_id:string;retrieved_at:string;master_updated_at:string|null;legals_updated_at:string|null;pluto_updated_at:string|null;master_rows:number;legal_rows:number;pluto_rows:number;manifest_json:string}|undefined; }
function sources(row: NonNullable<ReturnType<typeof latest>>): AcrisSourceMetadata[] { const source=(source:AcrisSourceMetadata['source'],datasetId:AcrisSourceMetadata['datasetId'],url:string,publisherUpdatedAt:string|null):AcrisSourceMetadata=>({source,datasetId,datasetUrl:url,publisherUpdatedAt,retrievedAt:row.retrieved_at,snapshotId:row.snapshot_id,caveat:'Immutable bounded local snapshot. NYC ACRIS covers four boroughs; Staten Island is not covered.'}); return [source('NYC_ACRIS_MASTER','bnx9-e6tj',MASTER,row.master_updated_at),source('NYC_ACRIS_LEGALS','8h5j-fqxa',LEGALS,row.legals_updated_at),source('NYC_PLUTO','64uk-42ks',PLUTO,row.pluto_updated_at)]; }
export function acrisSummaryFor(db: DatabaseSync): AcrisSummaryData & { documentCount:number; exactDeedRows:number; duplicateMasterRows:number; excludedTypeRows:number; excludedTypeCounts:Record<string,number>; associationCount:number; associations:number; cells:AcrisCellCount[] } {
  const row=latest(db); const empty={window:{startInclusive:'2024-07-01',endExclusive:'2026-07-01'},distinctDocuments:0,documentCount:0,exactDeedRows:0,duplicateMasterRows:0,excludedTypeRows:0,excludedTypeCounts:{},associationCount:0,associations:0,cells:[],quality:{masterRows:0,acceptedDocuments:0,duplicateMasterRows:0,excludedRawTypeCounts:{},legalRows:0,duplicateLegalRows:0,invalidBblRows:0,deedsWithoutLegals:0,distinctLegalBbls:0,unmatchedBbls:0,plutoUnmatchedBbl:0,nullCoordinateBbls:0,coordinateNull:0,placedDocumentCells:0,multiBblDocuments:0,caveats:[]},sources:[],permitRankingTreatment:'SEPARATE_RECORDED_DEED_CONTEXT' as const,disclosure:'ACRIS recorded-deed context: four boroughs; Staten Island is not covered.'};
  if (!row) return empty; const result=value(db,row.snapshot_id,'result',{}) as AcrisIngestResult; const unmatched=result.unmatchedBbls??0,nullCoordinates=result.nullCoordinateBbls??0,associationCount=(db.prepare('SELECT COUNT(*) AS n FROM acris_legal_associations').get() as {n:number}).n; const quality:AcrisQuality={masterRows:row.master_rows,acceptedDocuments:result.acceptedDocuments??0,duplicateMasterRows:result.duplicateMasterRows??0,excludedRawTypeCounts:result.excludedRawTypeCounts??{},legalRows:row.legal_rows,duplicateLegalRows:result.duplicateLegalRows??0,invalidBblRows:result.invalidBblRows??0,deedsWithoutLegals:result.deedsWithoutLegals??0,distinctLegalBbls:(db.prepare('SELECT COUNT(DISTINCT bbl) AS n FROM acris_legal_associations').get() as {n:number}).n,unmatchedBbls:unmatched,plutoUnmatchedBbl:unmatched,nullCoordinateBbls:nullCoordinates,coordinateNull:nullCoordinates,placedDocumentCells:result.placedDocumentCells??0,multiBblDocuments:result.multiBblDocuments??0,caveats:['Exact raw doc_type DEED only. document_amt is a principal debt/obligation and is never a sale price.','Counts are distinct documents citywide and once per H3; multi-BBL deeds remain multi-parcel evidence.']}; const cells=acrisCellsFor(db); const excluded=Object.values(quality.excludedRawTypeCounts).reduce((sum,n)=>sum+n,0); return {window:empty.window,distinctDocuments:quality.acceptedDocuments,documentCount:quality.acceptedDocuments,exactDeedRows:quality.acceptedDocuments+quality.duplicateMasterRows,duplicateMasterRows:quality.duplicateMasterRows,excludedTypeRows:excluded,excludedTypeCounts:quality.excludedRawTypeCounts,associationCount,associations:associationCount,cells,quality,sources:sources(row),permitRankingTreatment:'SEPARATE_RECORDED_DEED_CONTEXT',disclosure:empty.disclosure};
}
export function acrisCellsFor(db: DatabaseSync): Array<AcrisCellCount & {associationCount:number}> { return db.prepare(`SELECT c.h3_cell AS h3Cell,COUNT(DISTINCT c.document_id) AS documentCount,COUNT(DISTINCT l.association_id) AS associationCount,'PARCEL_CENTROID' AS precision FROM acris_document_cells c JOIN acris_legal_associations l ON l.document_id=c.document_id JOIN acris_parcels p ON p.bbl=l.bbl AND p.h3_cell=c.h3_cell GROUP BY c.h3_cell ORDER BY documentCount DESC,c.h3_cell`).all() as unknown as Array<AcrisCellCount & {associationCount:number}>; }
export function acrisDocumentFor(db: DatabaseSync, documentId: string): AcrisDocumentEvidence | null { const row=db.prepare('SELECT document_id,recorded_date,document_date FROM acris_documents WHERE document_id=?').get(documentId) as {document_id:string;recorded_date:string;document_date:string|null}|undefined; if(!row)return null; const bbls=(db.prepare('SELECT DISTINCT bbl FROM acris_legal_associations WHERE document_id=? ORDER BY bbl').all(documentId) as {bbl:string}[]).map(x=>x.bbl); const h3Cells=(db.prepare('SELECT h3_cell FROM acris_document_cells WHERE document_id=? ORDER BY h3_cell').all(documentId) as {h3_cell:string}[]).map(x=>x.h3_cell); return {documentId:row.document_id,recordedDate:row.recorded_date,documentDate:row.document_date,docType:'DEED',bbls,h3Cells,placementPrecision:h3Cells.length?'PARCEL_CENTROID':null,documentAmountDisclosure:'NOT_A_SALE_PRICE'}; }
