import type { DatabaseSync } from 'node:sqlite';
import type { ApprovalEvidence, CellSignal, Market, PermitEvidence, RecordDetail, SourceReport, SummaryData } from '../shared/contracts.js';
import { change } from '../domain/change.js';
import { months, WINDOWS } from '../domain/dates.js';
import { polygonFor } from '../domain/spatial.js';

type PermitRow = { id: string; market: Market; source: 'CHICAGO_PERMIT' | 'NYC_DOB_NOW'; event_date: string; permit_number: string | null; permit_type: string; reported_cost_cents: number | null; address: string | null; description: string | null; h3_cell: string | null; lat: number | null; lng: number | null; warnings_json: string; raw_json: string };
const dates = [WINDOWS.prior.start, WINDOWS.prior.endExclusive, WINDOWS.current.start, WINDOWS.current.endExclusive];
function typeWhere(permitType: string) { return permitType === 'ALL' ? { clause: '', params: [] as string[] } : { clause: ' AND permit_type = ?', params: [permitType] }; }
function comparable(db: DatabaseSync, market: Market): boolean { const reports = reportsFor(db, market).filter(r => r.source !== 'SBA_504'); return reports.length > 0 && reports.every(r => r.completeness === 'complete-query'); }
function countChange(db: DatabaseSync, market: Market, permitType: string, mapped: boolean | null) {
  const filter = typeWhere(permitType); const mapClause = mapped ? ' AND h3_cell IS NOT NULL' : mapped === false ? ' AND h3_cell IS NULL' : '';
  const row = db.prepare(`SELECT SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS prior, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS current FROM permits WHERE market = ?${mapClause}${filter.clause}`).get(dates[0], dates[1], dates[2], dates[3], market, ...filter.params) as { prior: number | null; current: number | null };
  return change(row.current ?? 0, row.prior ?? 0, comparable(db, market));
}
export function reportsFor(db: DatabaseSync, market: Market): SourceReport[] { return (db.prepare('SELECT report_json FROM source_reports WHERE market = ? ORDER BY source').all(market) as Array<{ report_json: string }>).map(x => JSON.parse(x.report_json) as SourceReport); }
export function summaryFor(db: DatabaseSync, market: Market, permitType: string): SummaryData {
  const typeRows = db.prepare('SELECT DISTINCT permit_type FROM permits WHERE market = ? ORDER BY permit_type').all(market) as Array<{ permit_type: string }>;
  const sourceReports = reportsFor(db, market); const approval = sbaFor(db, market);
  return { market, mode: sourceReports.some(r => r.mode === 'public') ? 'public' : 'synthetic', windows: WINDOWS, comparable: comparable(db, market), permitTypes: typeRows.map(x => x.permit_type), acceptedPermits: countChange(db, market, permitType, null), mappedPermits: countChange(db, market, permitType, true), unmappedPermits: countChange(db, market, permitType, false), sources: sourceReports, sba: approval };
}
export function cellsFor(db: DatabaseSync, market: Market, permitType: string) {
  const filter = typeWhere(permitType); const rows = db.prepare(`SELECT h3_cell, MIN(address) AS address, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS prior, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS current FROM permits WHERE market = ? AND h3_cell IS NOT NULL${filter.clause} GROUP BY h3_cell HAVING prior > 0 OR current > 0 ORDER BY current DESC, h3_cell`).all(dates[0], dates[1], dates[2], dates[3], market, ...filter.params) as Array<{ h3_cell: string; address: string | null; prior: number; current: number }>;
  // This endpoint drives both map and area list. Keep it to two grouped queries, rather than per-cell detail queries.
  const monthlyRows = db.prepare(`SELECT h3_cell, substr(event_date, 1, 7) AS month, COUNT(*) AS count FROM permits WHERE market = ? AND h3_cell IS NOT NULL${filter.clause} GROUP BY h3_cell, month`).all(market, ...filter.params) as Array<{ h3_cell: string; month: string; count: number }>;
  const perCellMonth = new Map<string, Map<string, number>>();
  for (const row of monthlyRows) { let byMonth = perCellMonth.get(row.h3_cell); if (!byMonth) { byMonth = new Map(); perCellMonth.set(row.h3_cell, byMonth); } byMonth.set(row.month, row.count); }
  const isComparable = comparable(db, market);
  const cells = rows.map(row => { const permitCount = change(row.current ?? 0, row.prior ?? 0, isComparable); const byMonth = perCellMonth.get(row.h3_cell) ?? new Map<string, number>(); return { market, h3Cell: row.h3_cell, label: row.address ? `Near ${row.address}` : `${market === 'NYC' ? 'NYC' : 'Chicago'} H3 ${row.h3_cell.slice(-5)}`, permitCount, monthly: months().map(month => ({ month, count: byMonth.get(month) ?? 0 })), lowVolume: permitCount.current + permitCount.previous < 5 } satisfies CellSignal; });
  return { cells, geojson: { type: 'FeatureCollection' as const, features: cells.map(cell => ({ type: 'Feature' as const, properties: { h3Cell: cell.h3Cell, current: cell.permitCount.current, label: cell.label }, geometry: { type: 'Polygon' as const, coordinates: polygonFor(cell.h3Cell) } })) } };
}
export function signalFor(db: DatabaseSync, market: Market, cell: string, permitType: string): CellSignal | null {
  const filter = typeWhere(permitType); const row = db.prepare(`SELECT SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS prior, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS current FROM permits WHERE market = ? AND h3_cell = ?${filter.clause}`).get(dates[0], dates[1], dates[2], dates[3], market, cell, ...filter.params) as { prior: number | null; current: number | null };
  if (!(row.prior ?? 0) && !(row.current ?? 0)) return null;
  const monthlyRows = db.prepare(`SELECT substr(event_date, 1, 7) AS month, COUNT(*) AS count FROM permits WHERE market = ? AND h3_cell = ?${filter.clause} GROUP BY month`).all(market, cell, ...filter.params) as Array<{ month: string; count: number }>;
  const values = new Map(monthlyRows.map(x => [x.month, x.count])); const permitCount = change(row.current ?? 0, row.prior ?? 0, comparable(db, market));
  const address = (db.prepare(`SELECT MIN(address) AS address FROM permits WHERE market = ? AND h3_cell = ?${filter.clause}`).get(market, cell, ...filter.params) as { address: string | null }).address;
  return { market, h3Cell: cell, label: address ? `Near ${address}` : `${market === 'NYC' ? 'NYC' : 'Chicago'} H3 ${cell.slice(-5)}`, permitCount, monthly: months().map(month => ({ month, count: values.get(month) ?? 0 })), lowVolume: permitCount.current + permitCount.previous < 5 };
}
export function evidenceFor(db: DatabaseSync, market: Market, cell: string, type: string, period: 'prior' | 'current', limit: number, offset: number) {
  const filter = typeWhere(type); const w = WINDOWS[period]; const where = `market = ? AND h3_cell = ? AND event_date >= ? AND event_date < ?${filter.clause}`;
  const total = (db.prepare(`SELECT COUNT(*) AS n FROM permits WHERE ${where}`).get(market, cell, w.start, w.endExclusive, ...filter.params) as { n: number }).n;
  const rows = db.prepare(`SELECT * FROM permits WHERE ${where} ORDER BY event_date DESC, id LIMIT ? OFFSET ?`).all(market, cell, w.start, w.endExclusive, ...filter.params, limit, offset) as PermitRow[];
  return { data: rows.map(evidence), total };
}
function evidence(row: PermitRow): PermitEvidence { return { id: row.id, market: row.market, source: row.source, date: row.event_date, permitNumber: row.permit_number, permitType: row.permit_type, address: row.address, description: row.description, reportedCostCents: row.reported_cost_cents, h3Cell: row.h3_cell, point: row.lat === null || row.lng === null ? null : { lat: row.lat, lng: row.lng, precision: 'SOURCE_COORDINATE', provider: row.source }, warnings: JSON.parse(row.warnings_json) }; }
export function recordFor(db: DatabaseSync, id: string): RecordDetail | null {
  const permit = db.prepare('SELECT * FROM permits WHERE id = ?').get(id) as PermitRow | undefined;
  if (permit) return { id, normalized: evidence(permit), raw: JSON.parse(permit.raw_json), sourceUrl: permit.source === 'CHICAGO_PERMIT' ? `https://data.cityofchicago.org/resource/ydr8-5enu.json?id=${encodeURIComponent(permit.id.split(':')[1]!)}` : `https://data.cityofnewyork.us/resource/rbx6-tga4.json?$where=${encodeURIComponent(`source_row_id='${permit.id.split(':')[1]!}'`)}`, warnings: JSON.parse(permit.warnings_json) };
  const approval = db.prepare('SELECT * FROM approvals WHERE id = ?').get(id) as { market: Market; event_date: string; borrower_name: string | null; approval_amount_cents: number; loan_status: string | null; city: string; state: string; raw_json: string } | undefined;
  return approval ? { id, normalized: { id, market: approval.market, source: 'SBA_504', date: approval.event_date, borrowerName: approval.borrower_name, approvalAmountCents: approval.approval_amount_cents, status: approval.loan_status, city: approval.city, state: approval.state, geographyBasis: 'BORROWER_CITY' }, raw: JSON.parse(approval.raw_json), sourceUrl: 'https://data.sba.gov/dataset/7a-504-foia', warnings: ['Borrower-city context; not assigned to a permit cell.'] } : null;
}
export function approvalsFor(db: DatabaseSync, market: Market, period: 'prior' | 'current', limit: number, offset: number) { const w = WINDOWS[period]; const where = 'market = ? AND event_date >= ? AND event_date < ?'; const total = (db.prepare(`SELECT COUNT(*) AS n FROM approvals WHERE ${where}`).get(market, w.start, w.endExclusive) as { n: number }).n; const rows = db.prepare(`SELECT * FROM approvals WHERE ${where} ORDER BY event_date DESC, id LIMIT ? OFFSET ?`).all(market, w.start, w.endExclusive, limit, offset) as Array<{ id: string; market: Market; event_date: string; borrower_name: string | null; approval_amount_cents: number; loan_status: string | null; city: string; state: string }>;
  return { total, data: rows.map(x => ({ id: x.id, market: x.market, source: 'SBA_504' as const, date: x.event_date, borrowerName: x.borrower_name, approvalAmountCents: x.approval_amount_cents, status: x.loan_status, city: x.city, state: x.state, geographyBasis: 'BORROWER_CITY' as const })) }; }
function sbaFor(db: DatabaseSync, market: Market) { const source = reportsFor(db, market).find(r => r.source === 'SBA_504'); if (!source || source.status === 'unavailable') return { status: 'unavailable' as const, geographyLabel: 'SBA 504 city context unavailable', approvalCount: null, approvalAmountCents: null, note: source?.notes[0] ?? 'No verified SBA source was seeded.' }; const row = db.prepare('SELECT SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS pc, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN 1 ELSE 0 END) AS cc, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN approval_amount_cents ELSE 0 END) AS pa, SUM(CASE WHEN event_date >= ? AND event_date < ? THEN approval_amount_cents ELSE 0 END) AS ca FROM approvals WHERE market = ?').get(dates[0], dates[1], dates[2], dates[3], dates[0], dates[1], dates[2], dates[3], market) as { pc: number; cc: number; pa: number; ca: number }; return { status: 'available' as const, geographyLabel: market === 'CHICAGO' ? 'Chicago-labelled borrower city, Illinois; not a municipal-boundary match' : 'Five explicit borough-labelled borrower cities, New York; aliases such as Flushing are excluded', approvalCount: change(row.cc ?? 0, row.pc ?? 0, true), approvalAmountCents: change(row.ca ?? 0, row.pa ?? 0, true), note: 'SBA 504 approval records use verified borrower-city fields; approvals are not disbursements or permit-area activity. Loan status is later status as of 2026-06-30.' }; }
