import { describe, expect, it } from 'vitest';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fetchAcrisSnapshot } from '../scripts/acris-source.mjs';
import { refreshAcris } from '../scripts/refresh-acris.mjs';

function sourceId(url: URL) { return /resource\/([^/]+)\.json$/.exec(url.pathname)?.[1] ?? null; }
function sourcePublisher(rows: { master: Record<string, unknown>[]; legals: Record<string, unknown>[]; pluto: Record<string, unknown>[] }, calls: URL[]) {
  return async (input: URL | string) => {
    const url = new URL(String(input)); calls.push(url);
    if (/\/api\/views\//.test(url.pathname)) return new Response(JSON.stringify({ rowsUpdatedAt: 1_726_800_000 }), { status: 200 });
    const id = sourceId(url); const all = id === 'bnx9-e6tj' ? rows.master : id === '8h5j-fqxa' ? rows.legals : rows.pluto; const where = url.searchParams.get('$where') ?? ''; let selected = all;
    if (id === 'bnx9-e6tj') { const dates = [...where.matchAll(/'([^']+)'/g)].map(match => match[1]!); selected = all.filter(row => String(row.recorded_datetime) >= dates[0]! && String(row.recorded_datetime) < dates[1]!); }
    else if (id === '8h5j-fqxa') { const ids = [...where.matchAll(/'([^']+)'/g)].map(match => match[1]!); selected = all.filter(row => ids.includes(String(row.document_id))); }
    else if (id === '64uk-42ks') { const bbls = [...where.matchAll(/\d+/g)].map(match => match[0]!); selected = all.filter(row => bbls.includes(String(row.bbl).split('.')[0]!)); }
    if (url.searchParams.get('$select')?.includes('count(*)')) return new Response(JSON.stringify([{ count: String(selected.length) }]), { status: 200 });
    return new Response(JSON.stringify(selected.slice(0, Number(url.searchParams.get('$limit') ?? '50000'))), { status: 200 });
  };
}

describe('ACRIS staged refresh',()=>{
  it('does not fetch or rebuild when publisher versions match the checksum-verified active snapshot',async()=>{let fetched=0,rebuilt=0;const snapshot={snapshotId:'same',publisher:{master:{rowsUpdatedAt:1},legals:{rowsUpdatedAt:2},pluto:{rowsUpdatedAt:3}}};const result=await refreshAcris({getLocalSnapshot:()=>snapshot,getPublisherState:async()=>snapshot.publisher,fetchSnapshot:async()=>{fetched++;throw new Error('must not fetch');},rebuildDatabase:()=>{rebuilt++;},log:()=>{}});expect(result.outcome).toBe('UP_TO_DATE');expect(fetched).toBe(0);expect(rebuilt).toBe(0);});
  it('leaves the active pointer untouched when staged database verification fails',async()=>{let activated=false;await expect(refreshAcris({getLocalSnapshot:()=>null,getPublisherState:async()=>({master:{rowsUpdatedAt:1},legals:{rowsUpdatedAt:2},pluto:{rowsUpdatedAt:3}}),fetchSnapshot:async()=>({snapshotId:'next',complete:true,directory:'fixture'}),rebuildDatabase:()=>{throw new Error('fixture rebuild failure');},activateSnapshot:()=>{activated=true;},log:()=>{}})).rejects.toThrow(/fixture rebuild failure/);expect(activated).toBe(false);});
  it('restores the exact active pointer when an already-verified database cannot swap',async()=>{const events:string[]=[];let pointer='{"snapshotId":"old"}';const next={snapshotId:'next',complete:true,directory:'fixture'};await expect(refreshAcris({getLocalSnapshot:()=>null,getPublisherState:async()=>({master:{rowsUpdatedAt:1},legals:{rowsUpdatedAt:2},pluto:{rowsUpdatedAt:3}}),getStagedSnapshot:()=>next,fetchSnapshot:async()=>{throw new Error('must reuse staged snapshot');},pointerText:()=>pointer,prepareDatabase:()=>{events.push('prepare');return {active:'active.sqlite',staged:'next.sqlite'};},activateSnapshot:()=>{events.push('pointer-next');pointer='{"snapshotId":"next"}';},activateDatabase:()=>{events.push('swap');throw new Error('swap failed');},restorePointer:value=>{events.push('pointer-old');pointer=value;},discardDatabase:()=>events.push('discard'),log:()=>{}})).rejects.toThrow(/swap failed/);expect(pointer).toBe('{"snapshotId":"old"}');expect(events).toEqual(['prepare','pointer-next','swap','pointer-old','discard']);});
  it('retries the complete staged publisher version without another fetch',async()=>{let fetched=0,prepared=0;const publisher={master:{rowsUpdatedAt:1},legals:{rowsUpdatedAt:2},pluto:{rowsUpdatedAt:3}},next={snapshotId:'staged',complete:true,directory:'fixture'};await refreshAcris({getLocalSnapshot:()=>null,getPublisherState:async()=>publisher,getStagedSnapshot:state=>state===publisher?next:null,fetchSnapshot:async()=>{fetched++;throw new Error('must not fetch');},prepareDatabase:()=>{prepared++;return {active:'active.sqlite',staged:'next.sqlite'};},activateSnapshot:()=>{},activateDatabase:()=>{},discardDatabase:()=>{},log:()=>{}});expect(fetched).toBe(0);expect(prepared).toBe(1);});
  it('uses count-verified closed Master windows and count-verified Legal document batches without offsets or cursors',async()=>{const calls:URL[]=[];const rows={master:[{document_id:'same-time',doc_type:'DEED',recorded_datetime:'2025-01-02T12:00:00.000',document_date:'2025-01-01T00:00:00.000',document_amt:'1',good_through_date:'2026-01-01T00:00:00.000'},{document_id:'same-time',doc_type:'DEED',recorded_datetime:'2025-01-02T12:00:00.000',document_date:'2025-01-01T00:00:00.000',document_amt:'1',good_through_date:'2026-01-01T00:00:00.000'}],legals:[{document_id:'same-time',borough:'1',block:'1',lot:'1',easement:'N',partial_lot:'N',air_rights:'N',subterranean_rights:'N'}],pluto:[{bbl:'1000010001.00000000',latitude:'40.7',longitude:'-74.0'}]};const manifest=await fetchAcrisSnapshot({rawDirectory:mkdtempSync(join(tmpdir(),'radar-acris-live-')),fetchImpl:sourcePublisher(rows,calls),log:()=>{}});expect(manifest.counts).toMatchObject({master:{expected:2,fetched:2},legals:{fetched:1,requestedDocuments:1},pluto:{fetched:1,requestedBbls:1}});expect(manifest.extraction).toMatchObject({masterPagination:expect.stringContaining('count-verified closed windows'),legalPagination:expect.stringContaining('count-verified fixed document_id batches')});for(const call of calls.filter(url=>sourceId(url)))expect(call.searchParams.has('$offset')).toBe(false);expect(calls.filter(url=>sourceId(url)==='bnx9-e6tj'&&url.searchParams.get('$select')?.includes('count(*)'))).not.toHaveLength(0);expect(calls.filter(url=>sourceId(url)==='8h5j-fqxa'&&url.searchParams.get('$select')?.includes('count(*)'))).not.toHaveLength(0);});
});
