import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { canonicalAcrisBbl } from './nyc-acris-audit-lib.mjs';

export const ACRIS_WINDOW={startInclusive:'2024-07-01T00:00:00.000',endExclusive:'2026-07-01T00:00:00.000'};
const CLOSED_WINDOW_DAYS=14, SINGLE_QUERY_LIMIT=50_000;
export const acrisSources={master:{id:'bnx9-e6tj',source:'NYC_ACRIS_MASTER',fields:'document_id,doc_type,document_date,document_amt,recorded_datetime,modified_date,good_through_date'},legals:{id:'8h5j-fqxa',source:'NYC_ACRIS_LEGALS',fields:'document_id,borough,block,lot,easement,partial_lot,air_rights,subterranean_rights,good_through_date'},pluto:{id:'64uk-42ks',source:'NYC_PLUTO',fields:'bbl,latitude,longitude'}};
for(const source of Object.values(acrisSources)) source.base=`https://data.cityofnewyork.us/resource/${source.id}.json`;
const hash=value=>createHash('sha256').update(value).digest('hex'); const fileHash=path=>hash(readFileSync(path)); const json=path=>JSON.parse(readFileSync(path,'utf8'));
export function acrisSnapshotPaths(rawDirectory=resolve('data/raw')) { const root=resolve(rawDirectory,'acris');return {root,snapshots:resolve(root,'snapshots'),latest:resolve(root,'latest.json')}; }
export function acrisSnapshotAt(directory) { try { const manifest=json(resolve(directory,'manifest.json')); if(!manifest.complete||!manifest.snapshotId||!manifest.files)return null; for(const name of ['master','legals','pluto']) { const item=manifest.files[name],path=resolve(directory,item?.file??''); if(!item||!existsSync(path)||fileHash(path)!==item.sha256)return null; } return {...manifest,directory}; }catch{return null;} }
export function acrisLocalSnapshot(rawDirectory=resolve('data/raw')) { const paths=acrisSnapshotPaths(rawDirectory);try{const pointer=json(paths.latest);const snapshot=acrisSnapshotAt(resolve(paths.snapshots,String(pointer.snapshotId)));return snapshot?.snapshotId===pointer.snapshotId?snapshot:null;}catch{return null;} }
export function acrisStoredSnapshots(rawDirectory=resolve('data/raw')) { const paths=acrisSnapshotPaths(rawDirectory);if(!existsSync(paths.snapshots))return [];return readdirSync(paths.snapshots,{withFileTypes:true}).filter(x=>x.isDirectory()&&!x.name.startsWith('.')).map(x=>acrisSnapshotAt(resolve(paths.snapshots,x.name))).filter(Boolean).sort((a,b)=>`${a.retrievedAt}\0${a.snapshotId}`.localeCompare(`${b.retrievedAt}\0${b.snapshotId}`)); }
export function acrisStoredSnapshotsThrough(rawDirectory,target) { const all=acrisStoredSnapshots(rawDirectory);const index=all.findIndex(x=>x.snapshotId===target?.snapshotId);return index>=0?all.slice(0,index+1):target?[...all.filter(x=>`${x.retrievedAt}\0${x.snapshotId}`<=`${target.retrievedAt}\0${target.snapshotId}`),target].sort((a,b)=>`${a.retrievedAt}\0${a.snapshotId}`.localeCompare(`${b.retrievedAt}\0${b.snapshotId}`)):[]; }
export function activateAcrisSnapshot(snapshot,rawDirectory=resolve('data/raw')) { if(!snapshot?.directory||!acrisSnapshotAt(snapshot.directory))throw new Error('Cannot activate missing or checksum-invalid ACRIS snapshot.');const paths=acrisSnapshotPaths(rawDirectory);mkdirSync(paths.root,{recursive:true});const staged=`${paths.latest}.${process.pid}-${Date.now()}.staging`;writeFileSync(staged,JSON.stringify({snapshotId:snapshot.snapshotId,updatedAt:new Date().toISOString()},null,2));renameSync(staged,paths.latest); }
export function acrisPointerText(rawDirectory=resolve('data/raw')) { const {latest}=acrisSnapshotPaths(rawDirectory); return existsSync(latest)?readFileSync(latest,'utf8'):null; }
export function restoreAcrisPointer(pointerText,rawDirectory=resolve('data/raw')) { const paths=acrisSnapshotPaths(rawDirectory); if(pointerText===null){if(existsSync(paths.latest))rmSync(paths.latest,{force:true});return;} mkdirSync(paths.root,{recursive:true});const staged=`${paths.latest}.${process.pid}-${Date.now()}.restore`;writeFileSync(staged,pointerText);renameSync(staged,paths.latest); }
export async function requestJson(base,params={},fetchImpl=fetch) { const url=new URL(base);for(const [key,value] of Object.entries(params))url.searchParams.set(key,String(value));let error;for(let n=1;n<=3;n++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetchImpl(url,{signal:controller.signal});if(response.ok)return await response.json();error=new Error(`${response.status}: ${await response.text()}`);}catch(caught){error=caught;}finally{clearTimeout(timer);}if(n<3)await new Promise(done=>setTimeout(done,n*500));}throw error??new Error('NYC Open Data request failed.'); }
async function metadata(source,fetchImpl){const row=await requestJson(`https://data.cityofnewyork.us/api/views/${source.id}`,{},fetchImpl);return {id:source.id,source:source.source,rowsUpdatedAt:typeof row.rowsUpdatedAt==='number'?row.rowsUpdatedAt:null,apiUpdatedAt:typeof row.rowsUpdatedAt==='number'?new Date(row.rowsUpdatedAt*1000).toISOString():null};}
export async function acrisPublisherState(fetchImpl=fetch){const [master,legals,pluto]=await Promise.all(Object.values(acrisSources).map(source=>metadata(source,fetchImpl)));return {master,legals,pluto};}
export function acrisPublisherMatchesSnapshot(publisher,snapshot){return Boolean(snapshot&&['master','legals','pluto'].every(name=>publisher?.[name]?.rowsUpdatedAt!==null&&publisher?.[name]?.rowsUpdatedAt===snapshot.publisher?.[name]?.rowsUpdatedAt));}
export function acrisStoredSnapshotForPublisher(rawDirectory,publisher){return acrisStoredSnapshots(rawDirectory).filter(snapshot=>acrisPublisherMatchesSnapshot(publisher,snapshot)).at(-1)??null;}
async function count(source,where,fetchImpl){const rows=await requestJson(source.base,{'$select':'count(*) AS count','$where':where},fetchImpl);const value=Number(rows?.[0]?.count);if(!Number.isSafeInteger(value)||value<0)throw new Error(`${source.source} returned invalid count.`);return value;}
/**
 * Each Master request is a closed half-open time window that is fully returned in
 * one count-verified response. This deliberately avoids both offset scans and a
 * timestamp/document cursor: duplicate document IDs make either pagination scheme
 * unsafe unless the publisher supplies an audited unique row key.
 */
async function masterRows(fetchImpl,log){const rows=[];for(let start=Date.parse(ACRIS_WINDOW.startInclusive),end=Date.parse(ACRIS_WINDOW.endExclusive);start<end;start+=CLOSED_WINDOW_DAYS*86400000){const until=Math.min(start+CLOSED_WINDOW_DAYS*86400000,end),from=new Date(start).toISOString(),to=new Date(until).toISOString(),where=`recorded_datetime >= '${from}' AND recorded_datetime < '${to}'`,expected=await count(acrisSources.master,where,fetchImpl);if(expected>=SINGLE_QUERY_LIMIT)throw new Error(`NYC_ACRIS_MASTER closed ${from} window has ${expected} rows and reached the ${SINGLE_QUERY_LIMIT}-row safety cap; shrink the fixed window contract before activation.`);const page=await requestJson(acrisSources.master.base,{'$select':acrisSources.master.fields,'$where':where,'$order':'recorded_datetime ASC,document_id ASC','$limit':SINGLE_QUERY_LIMIT},fetchImpl);if(!Array.isArray(page)||page.length!==expected)throw new Error(`NYC_ACRIS_MASTER completeness mismatch for ${from}: expected ${expected}, got ${Array.isArray(page)?page.length:'non-array'}.`);rows.push(...page);log?.(`NYC_ACRIS_MASTER: ${rows.length}`);}return {rows,expected:rows.length};}
function chunks(values,size=300){return Array.from({length:Math.ceil(values.length/size)},(_,index)=>values.slice(index*size,index*size+size));}
async function rowsByDocumentIds(source,ids,fetchImpl,log){const rows=[];for(const group of chunks([...ids].sort(),350)){const where=`document_id IN(${group.map(id=>`'${id.replaceAll("'","''")}'`).join(',')})`,expected=await count(source,where,fetchImpl);if(expected>=SINGLE_QUERY_LIMIT)throw new Error(`${source.source} document batch reached the ${SINGLE_QUERY_LIMIT}-row safety cap; shrink the fixed batch contract before activation.`);const page=await requestJson(source.base,{'$select':source.fields,'$where':where,'$order':'document_id ASC,borough ASC,block ASC,lot ASC,easement ASC,partial_lot ASC,air_rights ASC,subterranean_rights ASC','$limit':SINGLE_QUERY_LIMIT},fetchImpl);if(!Array.isArray(page)||page.length!==expected)throw new Error(`${source.source} completeness mismatch: expected ${expected}, got ${Array.isArray(page)?page.length:'non-array'}.`);rows.push(...page);log?.(`${source.source}: ${rows.length}`);}return rows;}
async function plutoRows(bbls,fetchImpl,log){const rows=[];for(const group of chunks([...bbls].sort(),250)){const where=`bbl IN(${group.map(bbl=>String(BigInt(bbl))).join(',')})`;const expected=await count(acrisSources.pluto,where,fetchImpl);const page=await requestJson(acrisSources.pluto.base,{'$select':acrisSources.pluto.fields,'$where':where,'$order':'bbl ASC','$limit':5000},fetchImpl);if(!Array.isArray(page)||page.length!==expected)throw new Error('NYC_PLUTO BBL-scoped completeness mismatch.');rows.push(...page);log?.(`NYC_PLUTO: ${rows.length}`);}return rows;}
function writeJsonl(path,rows){writeFileSync(path,rows.map(row=>JSON.stringify(row)).join('\n')+(rows.length?'\n':''));}
/** Extraction only stages immutable raw data. `refreshAcris` alone advances the active pointer after database verification. */
export async function fetchAcrisSnapshot({rawDirectory=resolve('data/raw'),fetchImpl=fetch,log=console.log}={}) { const before=await acrisPublisherState(fetchImpl);log('STAGE FETCHING_ACRIS_MASTER');const master=await masterRows(fetchImpl,log);const exactIds=new Set(master.rows.filter(row=>String(row.doc_type??'').trim()==='DEED').map(row=>String(row.document_id??'').trim()).filter(Boolean));log('STAGE FETCHING_ACRIS_LEGALS');const legals=await rowsByDocumentIds(acrisSources.legals,exactIds,fetchImpl,log);const bbls=new Set(legals.map(row=>canonicalAcrisBbl(row.borough,row.block,row.lot)).filter(Boolean));log('STAGE FETCHING_ACRIS_PLUTO');const pluto=await plutoRows(bbls,fetchImpl,log);const after=await acrisPublisherState(fetchImpl);if(!['master','legals','pluto'].every(name=>before[name].rowsUpdatedAt!==null&&before[name].rowsUpdatedAt===after[name].rowsUpdatedAt))throw new Error('NYC ACRIS publisher changed during extraction; no snapshot was activated.');const digest=hash(JSON.stringify({publisher:before,master:master.rows,legals,pluto})).slice(0,16),snapshotId=`acris-${before.master.rowsUpdatedAt}-${before.legals.rowsUpdatedAt}-${before.pluto.rowsUpdatedAt}-${digest}`,paths=acrisSnapshotPaths(rawDirectory),finalDir=resolve(paths.snapshots,snapshotId),staging=resolve(paths.snapshots,`.staging-${snapshotId}.${process.pid}-${Date.now()}`);mkdirSync(paths.snapshots,{recursive:true});if(existsSync(finalDir)){const existing=acrisSnapshotAt(finalDir);if(!existing||existing.snapshotId!==snapshotId)throw new Error(`Refusing to overwrite immutable ACRIS snapshot ${snapshotId}.`);log(`STAGED_ACRIS_SNAPSHOT ${snapshotId}`);return existing;}mkdirSync(staging);try{const files={master:{file:'master.jsonl'},legals:{file:'legals.jsonl'},pluto:{file:'pluto.jsonl'}};for(const [name,rows] of Object.entries({master:master.rows,legals,pluto})){const file=resolve(staging,files[name].file);writeJsonl(file,rows);files[name].sha256=fileHash(file);files[name].rows=rows.length;}const manifest={snapshotId,complete:true,retrievedAt:new Date().toISOString(),window:ACRIS_WINDOW,publisher:before,sourceUrls:Object.fromEntries(Object.entries(acrisSources).map(([name,source])=>[name,source.base])),files,counts:{master:{expected:master.expected,fetched:master.rows.length},legals:{fetched:legals.length,requestedDocuments:exactIds.size},pluto:{fetched:pluto.length,requestedBbls:bbls.size}},extraction:{selectedFieldsOnly:true,masterPagination:`${CLOSED_WINDOW_DAYS}-day count-verified closed windows; no cursor or offset`,legalPagination:`count-verified fixed document_id batches of 350; no offset`,plutoScope:'BBLs referenced by exact-DEED Legal rows'}};writeFileSync(resolve(staging,'manifest.json'),JSON.stringify(manifest,null,2));renameSync(staging,finalDir);const result={...manifest,directory:finalDir};log(`STAGED_ACRIS_SNAPSHOT ${snapshotId}`);return result;}catch(error){if(existsSync(staging))rmSync(staging,{recursive:true,force:true});throw error;} }
