import { createReadStream, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { dirname, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { parse } from 'csv-parse';
import { latLngToCell } from 'h3-js';
import { seedZapFixture, seedZapLiveSnapshot } from './seed-zap-fixture.mjs';
import { zapLocalSnapshot, zapSnapshotAt, zapStoredSnapshotsThrough } from './zap-source.mjs';

const rawDirectory = process.env.RADAR_RAW_DIR ?? resolve('data/raw'); const demoDirectory = process.env.RADAR_DEMO_DIR ?? resolve('data/demo');
const p = { chicagoRaw: resolve(rawDirectory, 'chicago-permits-2024-07-01_2026-07-01.jsonl'), nycRaw: resolve(rawDirectory, 'nyc-permits-2024-07-01_2026-07-01.jsonl'), chicagoDemo: resolve(demoDirectory, 'chicago.jsonl'), nycDemo: resolve(demoDirectory, 'nyc.jsonl'), sba: process.env.RADAR_SBA_PATH ?? resolve(rawDirectory, 'sba_504_fy2010_present_asof_260630.csv') };
const full = existsSync(p.chicagoRaw) && existsSync(p.nycRaw); const dbPath = process.env.RADAR_DB_PATH ?? resolve('data/runtime/radar.sqlite');
const sourceUrl = { CHICAGO_PERMIT: 'https://data.cityofchicago.org/resource/ydr8-5enu.json', NYC_DOB_NOW: 'https://data.cityofnewyork.us/resource/rbx6-tga4.json', SBA_504: 'https://data.sba.gov/dataset/7a-504-foia' };
const text = x => typeof x === 'string' && x.trim() ? x.trim() : null; const num = x => typeof x === 'number' || (typeof x === 'string' && x.trim()) ? (Number.isFinite(Number(x)) ? Number(x) : null) : null; const day = x => { if(typeof x!=='string'||!/^\d{4}-\d{2}-\d{2}/.test(x))return null;const d=x.slice(0,10),v=new Date(`${d}T00:00:00Z`);return Number.isNaN(v.valueOf())||v.toISOString().slice(0,10)!==d?null:d; };
const inScope = x => x >= '2024-07-01' && x < '2026-07-01'; const validCoordinate = (market,lat,lng) => lat !== null && lng !== null && (market==='CHICAGO' ? lat>=41.6&&lat<=42.1&&lng>=-88&&lng<=-87.4 : lat>=40.45&&lat<=40.95&&lng>=-74.3&&lng<=-73.65); const h3 = (market,lat, lng) => validCoordinate(market,lat,lng) ? latLngToCell(lat, lng, 8) : null; const hash = file => createHash('sha256').update(readFileSync(file)).digest('hex');
function sourceReport(source, market, completeness, notes) { return { source, market, status: completeness === 'unavailable' ? 'unavailable' : 'available', mode: 'public', completeness, datasetUrl: sourceUrl[source], retrievedAt: full && source !== 'SBA_504' ? '2026-09-19T18:24:50.335Z' : null, publisherAsOf: source === 'SBA_504' ? '2026-06-30' : null, rowsRead: 0, acceptedRows: 0, rejectedRows: 0, duplicateRows: 0, outOfScopeRows: 0, resolvedRows: 0, unresolvedRows: 0, missingCostRows: 0, reasonCounts: {}, notes }; }
const reports = [sourceReport('CHICAGO_PERMIT','CHICAGO',full ? 'complete-query':'partial',[full ? 'Complete selected-field public extract; event unit is a recorded permit issuance.' : 'Bundled deterministic public sample; counts are sample counts.']), sourceReport('NYC_DOB_NOW','NYC',full ? 'complete-query':'partial',[full ? 'Complete selected-field DOB NOW Build extract; issuance records are not unique projects.' : 'Bundled deterministic public sample; counts are sample counts.']), sourceReport('SBA_504','CHICAGO',existsSync(p.sba) ? 'complete-query':'unavailable',[existsSync(p.sba) ? 'Verified 504 borrower-city context. Chicago label is not a municipal-boundary match.' : 'Verified SBA file is unavailable locally.']), sourceReport('SBA_504','NYC',existsSync(p.sba) ? 'complete-query':'unavailable',[existsSync(p.sba) ? 'Verified borrower-city context: New York, Brooklyn, Bronx, Queens, Staten Island.' : 'Verified SBA file is unavailable locally.'])];
const reportFor = (source, market) => reports.find(x => x.source === source && x.market === market); const why = (r, code) => { r.reasonCounts[code] = (r.reasonCounts[code] ?? 0) + 1; };
mkdirSync(dirname(dbPath), { recursive: true }); const db = new DatabaseSync(dbPath); db.exec(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS datasets(dataset_id TEXT PRIMARY KEY,imported_at TEXT NOT NULL,manifest_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS permits(id TEXT PRIMARY KEY,market TEXT NOT NULL,source TEXT NOT NULL,source_record_id TEXT NOT NULL,event_date TEXT NOT NULL,permit_number TEXT,permit_type TEXT NOT NULL,reported_cost_cents INTEGER,address TEXT,description TEXT,community_area TEXT,lat REAL,lng REAL,h3_cell TEXT,raw_json TEXT NOT NULL,warnings_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS permits_market_cell_date ON permits(market,h3_cell,event_date); CREATE INDEX IF NOT EXISTS permits_market_type_date ON permits(market,permit_type,event_date); CREATE TABLE IF NOT EXISTS approvals(id TEXT PRIMARY KEY,market TEXT NOT NULL,event_date TEXT NOT NULL,borrower_name TEXT,approval_amount_cents INTEGER NOT NULL,loan_status TEXT,city TEXT NOT NULL,state TEXT NOT NULL,raw_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS approvals_market_date ON approvals(market,event_date); CREATE TABLE IF NOT EXISTS source_reports(source TEXT NOT NULL,market TEXT NOT NULL,report_json TEXT NOT NULL,PRIMARY KEY(source,market));`);
const insertPermit = db.prepare('INSERT INTO permits VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); const insertApproval = db.prepare('INSERT INTO approvals VALUES(?,?,?,?,?,?,?,?,?)');
async function ingestPermits(file, source, market) { const r = reportFor(source,market); for await (const line of createInterface({ input:createReadStream(file), crlfDelay:Infinity })) { if (!line) continue; r.rowsRead++; let raw; try { raw=JSON.parse(line); } catch { r.rejectedRows++; why(r,'invalid_json'); continue; } const sourceId=text(source==='CHICAGO_PERMIT'?raw.id:raw.source_row_id), eventDate=day(source==='CHICAGO_PERMIT'?raw.issue_date:raw.issued_date); if(!sourceId||!eventDate){r.rejectedRows++;why(r,!sourceId?'missing_source_identity':'invalid_event_date');continue;} if(!inScope(eventDate)){r.outOfScopeRows++;continue;} const sourceLat=num(raw.latitude),sourceLng=num(raw.longitude),cell=h3(market,sourceLat,sourceLng),lat=cell?sourceLat:null,lng=cell?sourceLng:null,costRaw=num(source==='CHICAGO_PERMIT'?raw.reported_cost:raw.estimated_job_costs),cost=costRaw===null||costRaw<0?null:Math.round(costRaw*100); const row=source==='CHICAGO_PERMIT'?{number:text(raw.permit_),type:text(raw.permit_type)??'Unspecified',address:[text(raw.street_number),text(raw.street_direction),text(raw.street_name)].filter(Boolean).join(' ')||null,description:text(raw.work_description),community:text(raw.community_area),warnings:cell?[]:['Source coordinate unavailable or outside Chicago sanity bounds.']}:{number:text(raw.work_permit)??text(raw.job_filing_number),type:text(raw.work_type)??'Unspecified',address:[text(raw.house_no),text(raw.street_name),text(raw.borough)].filter(Boolean).join(' ')||null,description:text(raw.job_description),community:text(raw.borough),warnings:['DOB NOW Build issuance record; it is not a unique construction project.',...(cell?[]:['Source coordinate unavailable or outside NYC sanity bounds.'])]}; try{insertPermit.run(`${source}:${sourceId}`,market,source,sourceId,eventDate,row.number,row.type,cost,row.address,row.description,row.community,lat,lng,cell,JSON.stringify(raw),JSON.stringify(row.warnings));r.acceptedRows++;if(cell)r.resolvedRows++;else r.unresolvedRows++;if(cost===null)r.missingCostRows++;}catch(e){if(String(e).includes('UNIQUE')){r.duplicateRows++;why(r,'duplicate_identity');}else throw e;} } }
async function ingestSba(){if(!existsSync(p.sba))return;let n=0;for await(const raw of createReadStream(p.sba).pipe(parse({columns:true,bom:true,relax_column_count:true,skip_empty_lines:true}))){n++;for(const r of reports.filter(x=>x.source==='SBA_504'))r.rowsRead++;const d=day(raw.ApprovalDate),city=text(raw.BorrCity),state=text(raw.BorrState)?.toUpperCase(),amount=num(raw.GrossApproval);if(!d||!city||!state||amount===null||amount<0){for(const r of reports.filter(x=>x.source==='SBA_504')){r.rejectedRows++;why(r,'invalid_required_field');}continue;}if(!inScope(d)){for(const r of reports.filter(x=>x.source==='SBA_504'))r.outOfScopeRows++;continue;}const c=city.toUpperCase().replaceAll('.','').trim(), market=state==='IL'&&c==='CHICAGO'?'CHICAGO':state==='NY'&&['NEW YORK','BROOKLYN','BRONX','QUEENS','STATEN ISLAND'].includes(c)?'NYC':null;if(!market)continue;const r=reportFor('SBA_504',market), fingerprint=createHash('sha256').update(JSON.stringify(raw)).digest('hex').slice(0,16),id=`SBA_504:${market}:snapshot-row-${n}:${fingerprint}`;try{insertApproval.run(id,market,d,text(raw.BorrName),Math.round(amount*100),text(raw.LoanStatus),city,state,JSON.stringify(raw));r.acceptedRows++;}catch(e){if(String(e).includes('UNIQUE')){r.duplicateRows++;why(r,'duplicate_identity');}else throw e;}}for(const r of reports.filter(x=>x.source==='SBA_504')){const unmatched=r.rowsRead-r.acceptedRows-r.rejectedRows-r.duplicateRows-r.outOfScopeRows;if(unmatched>0){r.outOfScopeRows+=unmatched;why(r,'geography_not_selected');}}}
const chicago=full?p.chicagoRaw:p.chicagoDemo, nyc=full?p.nycRaw:p.nycDemo;if(!existsSync(chicago)||!existsSync(nyc))throw new Error('Permit sources missing. Fetch both public sources or generate public demo extracts.');const datasetId=full?`public-full-${hash(chicago).slice(0,12)}-${hash(nyc).slice(0,12)}`:JSON.parse(readFileSync('data/demo/manifest.json','utf8')).id;
const explicitZap=process.env.RADAR_ZAP_SNAPSHOT_DIR?zapSnapshotAt(process.env.RADAR_ZAP_SNAPSHOT_DIR):null;if(process.env.RADAR_ZAP_SNAPSHOT_DIR&&!explicitZap)throw new Error('RADAR_ZAP_SNAPSHOT_DIR is missing or checksum-invalid.');const activeTarget=explicitZap??zapLocalSnapshot(rawDirectory);const zapSnapshots=activeTarget?zapStoredSnapshotsThrough(rawDirectory,activeTarget):[];const activeZap=zapSnapshots.at(-1)??null;try{db.exec('BEGIN IMMEDIATE;DELETE FROM permits;DELETE FROM approvals;DELETE FROM source_reports;DELETE FROM datasets;');await ingestPermits(chicago,'CHICAGO_PERMIT','CHICAGO');await ingestPermits(nyc,'NYC_DOB_NOW','NYC');await ingestSba();if(zapSnapshots.length)zapSnapshots.forEach((snapshot,index)=>seedZapLiveSnapshot(db,snapshot,index===0));else seedZapFixture(db);for(const r of reports)db.prepare('INSERT INTO source_reports VALUES(?,?,?)').run(r.source,r.market,JSON.stringify(r));const manifest={id:datasetId,mode:'public',markets:['CHICAGO','NYC'],coverageStart:'2024-07-01',coverageEndExclusive:'2026-07-01',input:full?'complete local raw snapshots':'bundled public retained samples',zapInput:activeZap?`${zapSnapshots.length} complete immutable snapshots; active ${activeZap.snapshotId}`:'bundled deterministic fixture',sources:reports};db.prepare('INSERT INTO datasets VALUES(?,?,?)').run(datasetId,new Date().toISOString(),JSON.stringify(manifest));db.exec('COMMIT');console.log(`Seeded ${datasetId}: Chicago ${reportFor('CHICAGO_PERMIT','CHICAGO').acceptedRows}, NYC ${reportFor('NYC_DOB_NOW','NYC').acceptedRows}, ZAP ${activeZap?activeZap.snapshotId:'fixture'}.`);}catch(e){try{db.exec('ROLLBACK');}catch{}throw e;}finally{db.close();}
